controllers:
    resource: ../src/Controller/
    type: attribute

#front:
#    resource: 'routes/front.yaml'
#    prefix: /{_locale}
#    requirements:
#        _locale: '%app_locales%'

profile:
    path: '/profil'
    controller: App\Controller\ProfileController::index
    methods: ['GET']

profile_edit:
    path: '/profil/modifier'
    controller: App\Controller\ProfileController::edit
    methods: ['GET', 'POST']
# config/routes.yaml
download_article_pdf:
    path: '/article/{id}/download-pdf'
    controller: 'App\Controller\ArticleController::downloadPdf'
navbar:
    path: '/navbar'
    controller: App\Controller\NavBarController::index
    methods: ['GET']