controllers:
  resource: ../src/Controller/
  type: attribute

front:
  resource: 'front.yaml'
  prefix: /{_locale}
  requirements:
    _locale: '%app_locales%'

profile:
  path: '/profil'
  controller: App\Controller\ProfileController::index
  methods: ['GET']

profile_edit:
  path: '/profil/modifier'
  controller: App\Controller\ProfileController::edit
  methods: ['GET', 'POST']

download_article_pdf:
    path: '/download-article-pdf/{id}'
    controller: 'App\Controller\ArticleController::downloadArticlePdf'
navbar:
    path: '/navbar'
    controller: App\Controller\NavBarController::index
    methods: ['GET']
