parameters:
    locale: 'en'
    app_locales: en|fr
    brochures_directory: 'media/products'
services:
    App\Controller\CRUDPostsController:
        tags: ['controller.service_arguments']
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind: # defines the scalar arguments once and apply them to any service defined/created in this file
            $locales: '%app_locales%'
            #$defaultLocale: '%locale%'