profile:
  path: '/profil'
  controller: App\Controller\ProfileController::index
  methods: ['GET']

profile_edit:
  path: '/profil/modifier'
  controller: App\Controller\ProfileController::edit
  methods: ['GET', 'POST']
# config/routes.yaml
download_article_pdf:
  path: '/article/{id}/download-pdf'
  controller: 'App\Controller\ArticleController::downloadPdf'

app_login:
  path: /login
  controller: App\Controller\LoginController::index

app_article:
  path: /
  controller: App\Controller\ArticleController::index

app_profile:
  path: /profil
  controller: App\Controller\ProfileController::index
  methods: ['GET']

app_posts_create_controller:
  path: /posts/create
  controller: App\Controller\CRUDPostsController::create

app_posts_edit_controller:
  path: /posts/edit/{slug}
  controller: App\Controller\CRUDPostsController::edit

app_posts_delete_controller:
  path: /posts/delete/{slug}
  controller: App\Controller\CRUDPostsController::delete


app_posts_show_controller:
  path: /posts/show/{slug}
  controller: App\Controller\CRUDPostsController::show

app_ctag_index:
  path: /ctags
  controller: App\Controller\CtagController::index

app_ctag_create:
  path: /ctags/create
  controller: App\Controller\CtagController::create

app_ctag_edit:
  path: /ctags/edit/{id}
  controller: App\Controller\CtagController::edit

app_ctag_delete:
  path: /ctags/delete/{id}
  controller: App\Controller\CtagController::delete

app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

